apiVersion: apps/v1
kind: Deployment
metadata:
  name: devyapp-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: devyapp
  template:
    metadata:
      labels:
        app: devyapp
    spec:
      containers:
      - name: devyapp
        image: chiamakaobitube/devyapp:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 3000

  