branch-defaults:
  default:
    environment: devyapp
    group_suffix: null
  master:
    environment: devyApp
global:
  application_name: devyApp
  branch: null
  default_ec2_keyname: null
  default_platform: Node.js 12 running on 64bit Amazon Linux 2
  default_region: us-west-2
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: aws-user
  repository: null
  sc: null
  workspace_type: Application
